"""Temperature

Revision ID: 0d958df8273f
Revises: 975b743d7986
Create Date: 2024-12-14 14:02:04.082117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d958df8273f'
down_revision = '975b743d7986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temperature_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temperature_timestamp'))

    op.drop_table('temperature')
    # ### end Alembic commands ###
