"""Humidity

Revision ID: 469a06c57c4d
Revises: 0d958df8273f
Create Date: 2024-12-17 19:35:24.614097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469a06c57c4d'
down_revision = '0d958df8273f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humidity',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('humidity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_humidity_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('humidity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_humidity_timestamp'))

    op.drop_table('humidity')
    # ### end Alembic commands ###
