"""new fields in user model

Revision ID: 975b743d7986
Revises: 24a1cd0fb3b2
Create Date: 2024-10-15 15:24:43.441753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975b743d7986'
down_revision = '24a1cd0fb3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
